# Model arguments
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
bf16: true
tf32: true

# Dataset arguments
dataset_id_or_path: 'openai/gsm8k'

# Training arguments
max_steps: 50 # Original 450
num_train_epochs: 1
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-7
lr_scheduler_type: cosine
warmup_ratio: 0.03

# GRPO arguments
use_vllm: false
num_generations: 3
per_device_train_batch_size: 2
beta: 0.001
max_prompt_length: 256
max_completion_length: 512

# Logging arguments
logging_strategy: steps
logging_steps: 2
report_to:
- tensorboard
save_strategy: "steps"
save_steps: 25
seed: 42

# Script arguments
public_maddr: "/ip4/38.101.215.12/tcp/30002"
host_maddr: "/ip4/0.0.0.0/tcp/38331"
max_rounds: 10000

# Model-specific arguments
model_name_or_path: Gensyn/Qwen2.5-7B-Instruct
output_dir: runs/gsm8k/multinode/Qwen2.5-7B-Instruct-Gensyn-Swarm-rtx3090ti 